blank_issues_enabled: false
contact_links:
  - name: ✨ Feature Requests
    url: https://github.com/codingjoe/MusicBeam/discussions/categories/ideas
    about: Please use the GitHub Discussions to request new features.
  - name: 🙋 Questions & Help
    url: https://github.com/codingjoe/MusicBeam/discussions/categories/q-a
    about: Please use the GitHub Discussions to ask questions.
